apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: httpd
  - name: myapp2  


apiVersion: v1
kind: Pod
metadata:
  name: 01-sample
spec:
  containers:
  - name: myapp
    image: httpd 

